name: C/C++ CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++ pkg-config git liballegro4-dev
        allegro-config --version
        cmake --version
        ninja --version
    - name: make
      run: make DEBUG=YES
    - name: test
      run: make test DEBUG=YES
